name       : buildah
version    : 1.14.0
release    : 8
source     :
    - git|https://github.com/containers/buildah : v1.14.0
extract    : no
license    : Apache-2.0
homepage   : https://buildah.io/
component  : virt
summary    : A tool that facilitates building Open Container Initiative (OCI) container images
description: |
    The Buildah package provides a command line tool that can be used to
    - create a working container, either from scratch or using an image as a starting point
    - create an image, either from a working container or via the instructions in a Dockerfile
    - images can be built in either the OCI image format or the traditional upstream docker image format
    - mount a working container's root filesystem for manipulation
    - unmount a working container's root filesystem
    - use the updated contents of a container's root filesystem as a filesystem layer to create a new image
    - delete a working container or an image
    - rename a local container
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gpgme)
    - pkgconfig(libseccomp)
    - btrfs-progs-devel
    - golang
    - go-md2man
rundeps    :
    - bzip2
    - cni-plugins
    - runc
    - skopeo
environment: |
    export GOPATH=$PKG_BUILD_DIR
    export SRC_DIR=$GOPATH/src/github.com/containers
setup      : |
    mkdir -p $SRC_DIR
    cp -r $sources/buildah.git/. $SRC_DIR
build      : |
    %make -C $SRC_DIR
install    : |
    %make_install -C $SRC_DIR PREFIX=%PREFIX%
